# we are extending everything from tomcat:7.0 image ...
FROM tomcat:7.0

# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY ./target/custom-filter-chain.war /usr/local/tomcat/webapps/custom-filter-chain.war